### ISSUE TITLE
Car image is missing

### ISSUE THREAD

**Issue by joachimdekker** [TheCodeMage/profielwerkstuk#13]
When running the code, I get the following error on runtime:
`Traceback (most recent call last):
  File "C:\Users\famde\AppData\Roaming\Python\Python37\site-packages\pyglet\resource.py", line 453, in file
    location = self._index[name]
KeyError: '../Images/car.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/famde/OneDrive/Documenten/VS Code/Profielwerkstuk+/profielwerkstuk/car.py", line 120, in <module>
    x.run()
  File "c:/Users/famde/OneDrive/Documenten/VS Code/Profielwerkstuk+/profielwerkstuk/car.py", line 114, in run
    self.render()
  File "c:/Users/famde/OneDrive/Documenten/VS Code/Profielwerkstuk+/profielwerkstuk/car.py", line 90, in render
    self.CAR.drawCar()
  File "c:/Users/famde/OneDrive/Documenten/VS Code/Profielwerkstuk+/profielwerkstuk/car.py", line 18, in drawCar
    self.car = pyglet.sprite.Sprite(pyglet.resource.image('../Images/car.png'), x=self.x_coord, y=self.y_coord)
  File "C:\Users\famde\AppData\Roaming\Python\Python37\site-packages\pyglet\resource.py", line 575, in image
    identity = self._cached_images[name] = self._alloc_image(name, atlas, border)
  File "C:\Users\famde\AppData\Roaming\Python\Python37\site-packages\pyglet\resource.py", line 500, in _alloc_image
    file = self.file(name)
  File "C:\Users\famde\AppData\Roaming\Python\Python37\site-packages\pyglet\resource.py", line 456, in file
    raise ResourceNotFoundException(name)
pyglet.resource.ResourceNotFoundException: Resource "../Images/car.png" was not found on the path.  Ensure that the filename has the correct captialisation.`

This problem can be easily resolved by adding the car image to the repository. @Tboefijn

**Comment by joachimdekker** [comment]
For clarity:
This only happens in the fork [tboefijn/issue3](https://github.com/TheCodeMage/profielwerkstuk/tree/Tboefijn/issue3)
